package model.bean;
// Generated 24/05/2018 23:34:16 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Categoria generated by hbm2java
 */
public class Categoria  implements java.io.Serializable {


     private Integer id;
     private String nome;
     private Date insertDt;
     private Set produtos = new HashSet(0);

    public Categoria() {
    }

    public Categoria(String nome, Date insertDt, Set produtos) {
       this.nome = nome;
       this.insertDt = insertDt;
       this.produtos = produtos;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getInsertDt() {
        return this.insertDt;
    }
    
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }
    public Set getProdutos() {
        return this.produtos;
    }
    
    public void setProdutos(Set produtos) {
        this.produtos = produtos;
    }




}


