package model.bean;
// Generated 24/05/2018 23:34:16 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Produto generated by hbm2java
 */
public class Produto  implements java.io.Serializable {


     private Integer id;
     private Categoria categoria;
     private String nome;
     private Date insertDt;

    public Produto() {
    }

    public Produto(Categoria categoria, String nome, Date insertDt) {
       this.categoria = categoria;
       this.nome = nome;
       this.insertDt = insertDt;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Categoria getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(Categoria categoria) {
        this.categoria = categoria;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Date getInsertDt() {
        return this.insertDt;
    }
    
    public void setInsertDt(Date insertDt) {
        this.insertDt = insertDt;
    }




}


